import type {
  Appointment,
  Customer,
  Product,
  QueueTicket,
  Sale,
  Service,
  StaffMember,
  Tenant,
} from "@/entities/types";

export const tenant: Tenant = {
  id: "t_001",
  name: "Atelier Barber Co.",
  slug: "atelier",
  plan: "growth",
  currency: "USD",
};

export const staff: StaffMember[] = [
  {
    id: "s1",
    name: "Mateo Álvarez",
    role: "BARBER",
    commissionPct: 45,
    availableForBooking: true,
    avatarColor: "oklch(0.66 0.18 268)",
    specialties: ["Fade", "Beard"],
  },
  {
    id: "s2",
    name: "Lucía Romero",
    role: "SPECIALIST",
    commissionPct: 50,
    availableForBooking: true,
    avatarColor: "oklch(0.68 0.16 155)",
    specialties: ["Color", "Styling"],
  },
  {
    id: "s3",
    name: "Diego Funes",
    role: "BARBER",
    commissionPct: 42,
    availableForBooking: true,
    avatarColor: "oklch(0.78 0.15 75)",
    specialties: ["Classic Cut"],
  },
  {
    id: "s4",
    name: "Iván Soto",
    role: "BARBER",
    commissionPct: 40,
    availableForBooking: false,
    avatarColor: "oklch(0.68 0.14 230)",
    specialties: ["Kids"],
  },
  {
    id: "s5",
    name: "Sofía Castro",
    role: "ADMIN",
    commissionPct: 0,
    availableForBooking: false,
    avatarColor: "oklch(0.62 0.21 25)",
    specialties: [],
  },
];

export const customers: Customer[] = [
  {
    id: "c1",
    name: "Tomás Herrera",
    phone: "+54 11 5520-1190",
    email: "tomas@mail.com",
    blocked: false,
    visits: 14,
    lifetimeValue: 820,
    lastVisit: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6),
  },
  {
    id: "c2",
    name: "Camila Ruiz",
    phone: "+54 11 5520-2233",
    blocked: false,
    visits: 9,
    lifetimeValue: 540,
    lastVisit: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
  },
  {
    id: "c3",
    name: "Joaquín Méndez",
    phone: "+54 11 5520-9911",
    blocked: false,
    visits: 2,
    lifetimeValue: 90,
    lastVisit: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30),
  },
  {
    id: "c4",
    name: "Valentina Paz",
    phone: "+54 11 5520-4422",
    blocked: true,
    visits: 1,
    lifetimeValue: 45,
    notes: "No-show repetido",
  },
  {
    id: "c5",
    name: "Bruno Ibáñez",
    phone: "+54 11 5520-7788",
    blocked: false,
    visits: 22,
    lifetimeValue: 1340,
  },
  {
    id: "c6",
    name: "Renata Vidal",
    phone: "+54 11 5520-3300",
    blocked: false,
    visits: 5,
    lifetimeValue: 260,
  },
];

export const services: Service[] = [
  {
    id: "sv1",
    name: "Corte Clásico",
    durationMin: 30,
    basePrice: 25,
    active: true,
    allowedRoles: ["BARBER", "SPECIALIST"],
  },
  {
    id: "sv2",
    name: "Corte + Barba",
    durationMin: 45,
    basePrice: 38,
    active: true,
    allowedRoles: ["BARBER"],
  },
  {
    id: "sv3",
    name: "Fade Premium",
    durationMin: 50,
    basePrice: 45,
    active: true,
    allowedRoles: ["BARBER"],
  },
  {
    id: "sv4",
    name: "Color & Styling",
    durationMin: 90,
    basePrice: 80,
    active: true,
    allowedRoles: ["SPECIALIST"],
  },
  {
    id: "sv5",
    name: "Afeitado Tradicional",
    durationMin: 30,
    basePrice: 28,
    active: true,
    allowedRoles: ["BARBER"],
  },
  {
    id: "sv6",
    name: "Tratamiento Capilar",
    durationMin: 40,
    basePrice: 35,
    active: false,
    allowedRoles: ["SPECIALIST"],
  },
];

export const products: Product[] = [
  {
    id: "p1",
    sku: "POM-001",
    name: "Pomada Mate 100ml",
    price: 22,
    stock: 18,
    active: true,
    lowStockThreshold: 6,
  },
  {
    id: "p2",
    sku: "SHA-014",
    name: "Shampoo Reparador 250ml",
    price: 28,
    stock: 4,
    active: true,
    lowStockThreshold: 6,
  },
  {
    id: "p3",
    sku: "OIL-003",
    name: "Aceite para Barba",
    price: 19,
    stock: 11,
    active: true,
    lowStockThreshold: 5,
  },
  {
    id: "p4",
    sku: "GEL-008",
    name: "Gel Fijación Fuerte",
    price: 14,
    stock: 0,
    active: true,
    lowStockThreshold: 4,
  },
  {
    id: "p5",
    sku: "WAX-002",
    name: "Cera Mate Premium",
    price: 26,
    stock: 9,
    active: true,
    lowStockThreshold: 4,
  },
];

const today = new Date();
const at = (h: number, m = 0) => {
  const d = new Date(today);
  d.setHours(h, m, 0, 0);
  return d;
};

export const appointments: Appointment[] = [
  {
    id: "a1",
    customerId: "c1",
    staffId: "s1",
    serviceIds: ["sv2"],
    start: at(9, 0),
    end: at(9, 45),
    status: "completed",
  },
  {
    id: "a2",
    customerId: "c2",
    staffId: "s2",
    serviceIds: ["sv4"],
    start: at(10, 0),
    end: at(11, 30),
    status: "in_progress",
  },
  {
    id: "a3",
    customerId: "c3",
    staffId: "s3",
    serviceIds: ["sv1"],
    start: at(11, 0),
    end: at(11, 30),
    status: "checked_in",
  },
  {
    id: "a4",
    customerId: "c5",
    staffId: "s1",
    serviceIds: ["sv3"],
    start: at(12, 0),
    end: at(12, 50),
    status: "scheduled",
  },
  {
    id: "a5",
    customerId: "c6",
    staffId: "s3",
    serviceIds: ["sv1", "sv5"],
    start: at(13, 30),
    end: at(14, 30),
    status: "scheduled",
  },
  {
    id: "a6",
    customerId: "c1",
    staffId: "s2",
    serviceIds: ["sv4"],
    start: at(15, 0),
    end: at(16, 30),
    status: "scheduled",
  },
  {
    id: "a7",
    customerId: "c2",
    staffId: "s1",
    serviceIds: ["sv2"],
    start: at(17, 0),
    end: at(17, 45),
    status: "scheduled",
  },
];

export const queue: QueueTicket[] = [
  {
    id: "q1",
    customerId: "c3",
    serviceId: "sv1",
    waitingSince: new Date(Date.now() - 1000 * 60 * 8),
  },
  {
    id: "q2",
    customerId: "c6",
    serviceId: "sv2",
    preferredStaffId: "s1",
    waitingSince: new Date(Date.now() - 1000 * 60 * 14),
  },
  {
    id: "q3",
    customerId: "c5",
    serviceId: "sv3",
    waitingSince: new Date(Date.now() - 1000 * 60 * 22),
  },
];

export const sales: Sale[] = [
  {
    id: "sl1",
    number: "T-1042",
    customerId: "c1",
    staffId: "s1",
    items: [
      {
        id: "i1",
        kind: "service",
        refId: "sv2",
        name: "Corte + Barba",
        qty: 1,
        unitPrice: 38,
      },
      {
        id: "i2",
        kind: "product",
        refId: "p1",
        name: "Pomada Mate 100ml",
        qty: 1,
        unitPrice: 22,
      },
    ],
    status: "open",
    openedAt: new Date(Date.now() - 1000 * 60 * 12),
  },
  {
    id: "sl2",
    number: "T-1043",
    customerId: "c2",
    staffId: "s2",
    items: [
      {
        id: "i3",
        kind: "service",
        refId: "sv4",
        name: "Color & Styling",
        qty: 1,
        unitPrice: 80,
      },
    ],
    status: "open",
    openedAt: new Date(Date.now() - 1000 * 60 * 4),
  },
  {
    id: "sl3",
    number: "T-1041",
    customerId: "c5",
    staffId: "s3",
    items: [
      {
        id: "i4",
        kind: "service",
        refId: "sv1",
        name: "Corte Clásico",
        qty: 1,
        unitPrice: 25,
      },
      {
        id: "i5",
        kind: "product",
        refId: "p3",
        name: "Aceite para Barba",
        qty: 1,
        unitPrice: 19,
      },
    ],
    status: "paid",
    paymentMethod: "card",
    openedAt: new Date(Date.now() - 1000 * 60 * 90),
    closedAt: new Date(Date.now() - 1000 * 60 * 78),
  },
  {
    id: "sl4",
    number: "T-1040",
    customerId: "c6",
    staffId: "s1",
    items: [
      {
        id: "i6",
        kind: "service",
        refId: "sv3",
        name: "Fade Premium",
        qty: 1,
        unitPrice: 45,
      },
    ],
    status: "paid",
    paymentMethod: "cash",
    openedAt: new Date(Date.now() - 1000 * 60 * 160),
    closedAt: new Date(Date.now() - 1000 * 60 * 150),
  },
];
